### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by donohfx** [thioden/gc_gen_cli#1]
## Issue

Add progress bar to track how far along process is.

**Comment by Brianshayne** [comment]
THIS IS VERY IMPORTANT @thioden FIX IT NOW

**Comment by Brianshayne** [comment]
WHY U NO FIX THIS YET?

**Comment by Brianshayne** [comment]
STILL NOT FIXED.

**Comment by thioden** [comment]
USE THIS

```
import sys
from time import sleep 

print "Progress"
while True:
    sys.stdout.write("#")
    sys.stdout.flush()  
    sleep(1)
```

**Comment by donohfx** [comment]
Where's the pull request?! Merge it into your source!

**Comment by donohfx** [comment]
<3 lololol

**Comment by thioden** [comment]
RUN IT

**Comment by Brianshayne** [comment]
Ill run you.

- Brian Donohue | Shopify Plus
<http://t.sidekickopen34.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3N1t4YN5v0zBHd7qvbW2BFNn256dLstdQVVvj02?t=http%3A%2F%2Fshopify.ca%2Fplus&si=5670990270431232&pi=83d0146e-9957-4313-b132-f07969d7dedc>
 | Book a Call
<http://t.sidekickopen34.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3N1t4YN5v0zBHd7qvbW2BFNn256dLstdQVVvj02?t=http%3A%2F%2Fbrian-donohue.youcanbook.me%2F&si=5670990270431232&pi=83d0146e-9957-4313-b132-f07969d7dedc>
